name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - '**' # Deploy previews for all branches
  pull_request:

concurrency:
  group: vercel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel environment info (Preview)
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        run: vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"

      - name: Pull Vercel environment info (Production)
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: vercel pull --yes --environment=production --token "$VERCEL_TOKEN"

      - name: Build (Preview)
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        run: vercel build --token "$VERCEL_TOKEN"

      - name: Build (Production)
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: vercel build --prod --token "$VERCEL_TOKEN"

      - name: Deploy (Preview)
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        run: vercel deploy --prebuilt --token "$VERCEL_TOKEN"

      - name: Deploy (Production)
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"